/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as CallRouteImport } from './routes/call'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppFavoritesRouteImport } from './routes/_app.favorites'
import { Route as AppOnboardingRouteImport } from './routes/_app.onboarding'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppChatChar123ChatIdChar125RouteImport } from './routes/_app.chat.{-$chatId}'
import { Route as AppNewTabIdRouteImport } from './routes/_app.new-tab.$id'
import { Route as AppSettingsIndexRouteImport } from './routes/_app.settings.index'
import { Route as AppSettingsAppearanceRouteImport } from './routes/_app.settings.appearance'
import { Route as AppSettingsChatsRouteImport } from './routes/_app.settings.chats'
import { Route as AppSettingsDevelopmentRouteImport } from './routes/_app.settings.development'
import { Route as AppSettingsLanguageRouteImport } from './routes/_app.settings.language'
import { Route as AppProductIdChar123RouteChar125RouteImport } from './routes/_app.product.$id.{-$route}'
import { Route as AppSettingsDevelopmentCustomChainsRouteImport } from './routes/_app.settings.development.custom-chains'
import { Route as AppSettingsDevelopmentNetworkRouteImport } from './routes/_app.settings.development.network'
import { Route as AppSettingsDevelopmentUpdateChannelRouteImport } from './routes/_app.settings.development.update-channel'
import { Route as AppSettingsPrivacyAppsIndexRouteImport } from './routes/_app.settings.privacy.apps.index'
import { Route as AppSettingsPrivacyAppsProductIdRouteImport } from './routes/_app.settings.privacy.apps.$productId'
import { Route as AppSettingsPrivacyPermissionsIndexRouteImport } from './routes/_app.settings.privacy.permissions.index'
import { Route as AppSettingsPrivacyPermissionsPermissionIdRouteImport } from './routes/_app.settings.privacy.permissions.$permissionId'
import { Route as AppSettingsPrivacyAppsProductIdIndexRouteImport } from './routes/_app.settings.privacy.apps.$productId.index'
import { Route as AppSettingsPrivacyAppsProductIdPermissionIdRouteImport } from './routes/_app.settings.privacy.apps.$productId.$permissionId'
import { Route as AppSettingsPrivacyPermissionsPermissionIdIndexRouteImport } from './routes/_app.settings.privacy.permissions.$permissionId.index'
import { Route as AppSettingsPrivacyPermissionsPermissionIdProductIdRouteImport } from './routes/_app.settings.privacy.permissions.$permissionId.$productId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const CallRoute = CallRouteImport.update({
  id: '/call',
  path: '/call',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppChatChar123ChatIdChar125Route =
  AppChatChar123ChatIdChar125RouteImport.update({
    id: '/chat/{-$chatId}',
    path: '/chat/{-$chatId}',
    getParentRoute: () => AppRoute,
  } as any)
const AppNewTabIdRoute = AppNewTabIdRouteImport.update({
  id: '/new-tab/$id',
  path: '/new-tab/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAppearanceRoute = AppSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsChatsRoute = AppSettingsChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsDevelopmentRoute = AppSettingsDevelopmentRouteImport.update({
  id: '/development',
  path: '/development',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsLanguageRoute = AppSettingsLanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppProductIdChar123RouteChar125Route =
  AppProductIdChar123RouteChar125RouteImport.update({
    id: '/product/$id/{-$route}',
    path: '/product/$id/{-$route}',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsDevelopmentCustomChainsRoute =
  AppSettingsDevelopmentCustomChainsRouteImport.update({
    id: '/custom-chains',
    path: '/custom-chains',
    getParentRoute: () => AppSettingsDevelopmentRoute,
  } as any)
const AppSettingsDevelopmentNetworkRoute =
  AppSettingsDevelopmentNetworkRouteImport.update({
    id: '/network',
    path: '/network',
    getParentRoute: () => AppSettingsDevelopmentRoute,
  } as any)
const AppSettingsDevelopmentUpdateChannelRoute =
  AppSettingsDevelopmentUpdateChannelRouteImport.update({
    id: '/update-channel',
    path: '/update-channel',
    getParentRoute: () => AppSettingsDevelopmentRoute,
  } as any)
const AppSettingsPrivacyAppsIndexRoute =
  AppSettingsPrivacyAppsIndexRouteImport.update({
    id: '/privacy/apps/',
    path: '/privacy/apps/',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsPrivacyAppsProductIdRoute =
  AppSettingsPrivacyAppsProductIdRouteImport.update({
    id: '/privacy/apps/$productId',
    path: '/privacy/apps/$productId',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsPrivacyPermissionsIndexRoute =
  AppSettingsPrivacyPermissionsIndexRouteImport.update({
    id: '/privacy/permissions/',
    path: '/privacy/permissions/',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsPrivacyPermissionsPermissionIdRoute =
  AppSettingsPrivacyPermissionsPermissionIdRouteImport.update({
    id: '/privacy/permissions/$permissionId',
    path: '/privacy/permissions/$permissionId',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsPrivacyAppsProductIdIndexRoute =
  AppSettingsPrivacyAppsProductIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppSettingsPrivacyAppsProductIdRoute,
  } as any)
const AppSettingsPrivacyAppsProductIdPermissionIdRoute =
  AppSettingsPrivacyAppsProductIdPermissionIdRouteImport.update({
    id: '/$permissionId',
    path: '/$permissionId',
    getParentRoute: () => AppSettingsPrivacyAppsProductIdRoute,
  } as any)
const AppSettingsPrivacyPermissionsPermissionIdIndexRoute =
  AppSettingsPrivacyPermissionsPermissionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppSettingsPrivacyPermissionsPermissionIdRoute,
  } as any)
const AppSettingsPrivacyPermissionsPermissionIdProductIdRoute =
  AppSettingsPrivacyPermissionsPermissionIdProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => AppSettingsPrivacyPermissionsPermissionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/call': typeof CallRoute
  '/dashboard': typeof AppDashboardRoute
  '/favorites': typeof AppFavoritesRoute
  '/onboarding': typeof AppOnboardingRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/chat/{-$chatId}': typeof AppChatChar123ChatIdChar125Route
  '/new-tab/$id': typeof AppNewTabIdRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/chats': typeof AppSettingsChatsRoute
  '/settings/development': typeof AppSettingsDevelopmentRouteWithChildren
  '/settings/language': typeof AppSettingsLanguageRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/product/$id/{-$route}': typeof AppProductIdChar123RouteChar125Route
  '/settings/development/custom-chains': typeof AppSettingsDevelopmentCustomChainsRoute
  '/settings/development/network': typeof AppSettingsDevelopmentNetworkRoute
  '/settings/development/update-channel': typeof AppSettingsDevelopmentUpdateChannelRoute
  '/settings/privacy/apps/$productId': typeof AppSettingsPrivacyAppsProductIdRouteWithChildren
  '/settings/privacy/permissions/$permissionId': typeof AppSettingsPrivacyPermissionsPermissionIdRouteWithChildren
  '/settings/privacy/apps/': typeof AppSettingsPrivacyAppsIndexRoute
  '/settings/privacy/permissions/': typeof AppSettingsPrivacyPermissionsIndexRoute
  '/settings/privacy/apps/$productId/$permissionId': typeof AppSettingsPrivacyAppsProductIdPermissionIdRoute
  '/settings/privacy/permissions/$permissionId/$productId': typeof AppSettingsPrivacyPermissionsPermissionIdProductIdRoute
  '/settings/privacy/apps/$productId/': typeof AppSettingsPrivacyAppsProductIdIndexRoute
  '/settings/privacy/permissions/$permissionId/': typeof AppSettingsPrivacyPermissionsPermissionIdIndexRoute
}
export interface FileRoutesByTo {
  '/call': typeof CallRoute
  '/dashboard': typeof AppDashboardRoute
  '/favorites': typeof AppFavoritesRoute
  '/onboarding': typeof AppOnboardingRoute
  '/': typeof AppIndexRoute
  '/chat/{-$chatId}': typeof AppChatChar123ChatIdChar125Route
  '/new-tab/$id': typeof AppNewTabIdRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/chats': typeof AppSettingsChatsRoute
  '/settings/development': typeof AppSettingsDevelopmentRouteWithChildren
  '/settings/language': typeof AppSettingsLanguageRoute
  '/settings': typeof AppSettingsIndexRoute
  '/product/$id/{-$route}': typeof AppProductIdChar123RouteChar125Route
  '/settings/development/custom-chains': typeof AppSettingsDevelopmentCustomChainsRoute
  '/settings/development/network': typeof AppSettingsDevelopmentNetworkRoute
  '/settings/development/update-channel': typeof AppSettingsDevelopmentUpdateChannelRoute
  '/settings/privacy/apps': typeof AppSettingsPrivacyAppsIndexRoute
  '/settings/privacy/permissions': typeof AppSettingsPrivacyPermissionsIndexRoute
  '/settings/privacy/apps/$productId/$permissionId': typeof AppSettingsPrivacyAppsProductIdPermissionIdRoute
  '/settings/privacy/permissions/$permissionId/$productId': typeof AppSettingsPrivacyPermissionsPermissionIdProductIdRoute
  '/settings/privacy/apps/$productId': typeof AppSettingsPrivacyAppsProductIdIndexRoute
  '/settings/privacy/permissions/$permissionId': typeof AppSettingsPrivacyPermissionsPermissionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/call': typeof CallRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/favorites': typeof AppFavoritesRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/chat/{-$chatId}': typeof AppChatChar123ChatIdChar125Route
  '/_app/new-tab/$id': typeof AppNewTabIdRoute
  '/_app/settings/appearance': typeof AppSettingsAppearanceRoute
  '/_app/settings/chats': typeof AppSettingsChatsRoute
  '/_app/settings/development': typeof AppSettingsDevelopmentRouteWithChildren
  '/_app/settings/language': typeof AppSettingsLanguageRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/product/$id/{-$route}': typeof AppProductIdChar123RouteChar125Route
  '/_app/settings/development/custom-chains': typeof AppSettingsDevelopmentCustomChainsRoute
  '/_app/settings/development/network': typeof AppSettingsDevelopmentNetworkRoute
  '/_app/settings/development/update-channel': typeof AppSettingsDevelopmentUpdateChannelRoute
  '/_app/settings/privacy/apps/$productId': typeof AppSettingsPrivacyAppsProductIdRouteWithChildren
  '/_app/settings/privacy/permissions/$permissionId': typeof AppSettingsPrivacyPermissionsPermissionIdRouteWithChildren
  '/_app/settings/privacy/apps/': typeof AppSettingsPrivacyAppsIndexRoute
  '/_app/settings/privacy/permissions/': typeof AppSettingsPrivacyPermissionsIndexRoute
  '/_app/settings/privacy/apps/$productId/$permissionId': typeof AppSettingsPrivacyAppsProductIdPermissionIdRoute
  '/_app/settings/privacy/permissions/$permissionId/$productId': typeof AppSettingsPrivacyPermissionsPermissionIdProductIdRoute
  '/_app/settings/privacy/apps/$productId/': typeof AppSettingsPrivacyAppsProductIdIndexRoute
  '/_app/settings/privacy/permissions/$permissionId/': typeof AppSettingsPrivacyPermissionsPermissionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/call'
    | '/dashboard'
    | '/favorites'
    | '/onboarding'
    | '/settings'
    | '/chat/{-$chatId}'
    | '/new-tab/$id'
    | '/settings/appearance'
    | '/settings/chats'
    | '/settings/development'
    | '/settings/language'
    | '/settings/'
    | '/product/$id/{-$route}'
    | '/settings/development/custom-chains'
    | '/settings/development/network'
    | '/settings/development/update-channel'
    | '/settings/privacy/apps/$productId'
    | '/settings/privacy/permissions/$permissionId'
    | '/settings/privacy/apps/'
    | '/settings/privacy/permissions/'
    | '/settings/privacy/apps/$productId/$permissionId'
    | '/settings/privacy/permissions/$permissionId/$productId'
    | '/settings/privacy/apps/$productId/'
    | '/settings/privacy/permissions/$permissionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/call'
    | '/dashboard'
    | '/favorites'
    | '/onboarding'
    | '/'
    | '/chat/{-$chatId}'
    | '/new-tab/$id'
    | '/settings/appearance'
    | '/settings/chats'
    | '/settings/development'
    | '/settings/language'
    | '/settings'
    | '/product/$id/{-$route}'
    | '/settings/development/custom-chains'
    | '/settings/development/network'
    | '/settings/development/update-channel'
    | '/settings/privacy/apps'
    | '/settings/privacy/permissions'
    | '/settings/privacy/apps/$productId/$permissionId'
    | '/settings/privacy/permissions/$permissionId/$productId'
    | '/settings/privacy/apps/$productId'
    | '/settings/privacy/permissions/$permissionId'
  id:
    | '__root__'
    | '/_app'
    | '/call'
    | '/_app/dashboard'
    | '/_app/favorites'
    | '/_app/onboarding'
    | '/_app/settings'
    | '/_app/'
    | '/_app/chat/{-$chatId}'
    | '/_app/new-tab/$id'
    | '/_app/settings/appearance'
    | '/_app/settings/chats'
    | '/_app/settings/development'
    | '/_app/settings/language'
    | '/_app/settings/'
    | '/_app/product/$id/{-$route}'
    | '/_app/settings/development/custom-chains'
    | '/_app/settings/development/network'
    | '/_app/settings/development/update-channel'
    | '/_app/settings/privacy/apps/$productId'
    | '/_app/settings/privacy/permissions/$permissionId'
    | '/_app/settings/privacy/apps/'
    | '/_app/settings/privacy/permissions/'
    | '/_app/settings/privacy/apps/$productId/$permissionId'
    | '/_app/settings/privacy/permissions/$permissionId/$productId'
    | '/_app/settings/privacy/apps/$productId/'
    | '/_app/settings/privacy/permissions/$permissionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  CallRoute: typeof CallRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call': {
      id: '/call'
      path: '/call'
      fullPath: '/call'
      preLoaderRoute: typeof CallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/favorites': {
      id: '/_app/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat/{-$chatId}': {
      id: '/_app/chat/{-$chatId}'
      path: '/chat/{-$chatId}'
      fullPath: '/chat/{-$chatId}'
      preLoaderRoute: typeof AppChatChar123ChatIdChar125RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/new-tab/$id': {
      id: '/_app/new-tab/$id'
      path: '/new-tab/$id'
      fullPath: '/new-tab/$id'
      preLoaderRoute: typeof AppNewTabIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/appearance': {
      id: '/_app/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AppSettingsAppearanceRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/chats': {
      id: '/_app/settings/chats'
      path: '/chats'
      fullPath: '/settings/chats'
      preLoaderRoute: typeof AppSettingsChatsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/development': {
      id: '/_app/settings/development'
      path: '/development'
      fullPath: '/settings/development'
      preLoaderRoute: typeof AppSettingsDevelopmentRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/language': {
      id: '/_app/settings/language'
      path: '/language'
      fullPath: '/settings/language'
      preLoaderRoute: typeof AppSettingsLanguageRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/product/$id/{-$route}': {
      id: '/_app/product/$id/{-$route}'
      path: '/product/$id/{-$route}'
      fullPath: '/product/$id/{-$route}'
      preLoaderRoute: typeof AppProductIdChar123RouteChar125RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/development/custom-chains': {
      id: '/_app/settings/development/custom-chains'
      path: '/custom-chains'
      fullPath: '/settings/development/custom-chains'
      preLoaderRoute: typeof AppSettingsDevelopmentCustomChainsRouteImport
      parentRoute: typeof AppSettingsDevelopmentRoute
    }
    '/_app/settings/development/network': {
      id: '/_app/settings/development/network'
      path: '/network'
      fullPath: '/settings/development/network'
      preLoaderRoute: typeof AppSettingsDevelopmentNetworkRouteImport
      parentRoute: typeof AppSettingsDevelopmentRoute
    }
    '/_app/settings/development/update-channel': {
      id: '/_app/settings/development/update-channel'
      path: '/update-channel'
      fullPath: '/settings/development/update-channel'
      preLoaderRoute: typeof AppSettingsDevelopmentUpdateChannelRouteImport
      parentRoute: typeof AppSettingsDevelopmentRoute
    }
    '/_app/settings/privacy/apps/': {
      id: '/_app/settings/privacy/apps/'
      path: '/privacy/apps'
      fullPath: '/settings/privacy/apps/'
      preLoaderRoute: typeof AppSettingsPrivacyAppsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/privacy/apps/$productId': {
      id: '/_app/settings/privacy/apps/$productId'
      path: '/privacy/apps/$productId'
      fullPath: '/settings/privacy/apps/$productId'
      preLoaderRoute: typeof AppSettingsPrivacyAppsProductIdRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/privacy/permissions/': {
      id: '/_app/settings/privacy/permissions/'
      path: '/privacy/permissions'
      fullPath: '/settings/privacy/permissions/'
      preLoaderRoute: typeof AppSettingsPrivacyPermissionsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/privacy/permissions/$permissionId': {
      id: '/_app/settings/privacy/permissions/$permissionId'
      path: '/privacy/permissions/$permissionId'
      fullPath: '/settings/privacy/permissions/$permissionId'
      preLoaderRoute: typeof AppSettingsPrivacyPermissionsPermissionIdRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/privacy/apps/$productId/': {
      id: '/_app/settings/privacy/apps/$productId/'
      path: '/'
      fullPath: '/settings/privacy/apps/$productId/'
      preLoaderRoute: typeof AppSettingsPrivacyAppsProductIdIndexRouteImport
      parentRoute: typeof AppSettingsPrivacyAppsProductIdRoute
    }
    '/_app/settings/privacy/apps/$productId/$permissionId': {
      id: '/_app/settings/privacy/apps/$productId/$permissionId'
      path: '/$permissionId'
      fullPath: '/settings/privacy/apps/$productId/$permissionId'
      preLoaderRoute: typeof AppSettingsPrivacyAppsProductIdPermissionIdRouteImport
      parentRoute: typeof AppSettingsPrivacyAppsProductIdRoute
    }
    '/_app/settings/privacy/permissions/$permissionId/': {
      id: '/_app/settings/privacy/permissions/$permissionId/'
      path: '/'
      fullPath: '/settings/privacy/permissions/$permissionId/'
      preLoaderRoute: typeof AppSettingsPrivacyPermissionsPermissionIdIndexRouteImport
      parentRoute: typeof AppSettingsPrivacyPermissionsPermissionIdRoute
    }
    '/_app/settings/privacy/permissions/$permissionId/$productId': {
      id: '/_app/settings/privacy/permissions/$permissionId/$productId'
      path: '/$productId'
      fullPath: '/settings/privacy/permissions/$permissionId/$productId'
      preLoaderRoute: typeof AppSettingsPrivacyPermissionsPermissionIdProductIdRouteImport
      parentRoute: typeof AppSettingsPrivacyPermissionsPermissionIdRoute
    }
  }
}

interface AppSettingsDevelopmentRouteChildren {
  AppSettingsDevelopmentCustomChainsRoute: typeof AppSettingsDevelopmentCustomChainsRoute
  AppSettingsDevelopmentNetworkRoute: typeof AppSettingsDevelopmentNetworkRoute
  AppSettingsDevelopmentUpdateChannelRoute: typeof AppSettingsDevelopmentUpdateChannelRoute
}

const AppSettingsDevelopmentRouteChildren: AppSettingsDevelopmentRouteChildren =
  {
    AppSettingsDevelopmentCustomChainsRoute:
      AppSettingsDevelopmentCustomChainsRoute,
    AppSettingsDevelopmentNetworkRoute: AppSettingsDevelopmentNetworkRoute,
    AppSettingsDevelopmentUpdateChannelRoute:
      AppSettingsDevelopmentUpdateChannelRoute,
  }

const AppSettingsDevelopmentRouteWithChildren =
  AppSettingsDevelopmentRoute._addFileChildren(
    AppSettingsDevelopmentRouteChildren,
  )

interface AppSettingsPrivacyAppsProductIdRouteChildren {
  AppSettingsPrivacyAppsProductIdPermissionIdRoute: typeof AppSettingsPrivacyAppsProductIdPermissionIdRoute
  AppSettingsPrivacyAppsProductIdIndexRoute: typeof AppSettingsPrivacyAppsProductIdIndexRoute
}

const AppSettingsPrivacyAppsProductIdRouteChildren: AppSettingsPrivacyAppsProductIdRouteChildren =
  {
    AppSettingsPrivacyAppsProductIdPermissionIdRoute:
      AppSettingsPrivacyAppsProductIdPermissionIdRoute,
    AppSettingsPrivacyAppsProductIdIndexRoute:
      AppSettingsPrivacyAppsProductIdIndexRoute,
  }

const AppSettingsPrivacyAppsProductIdRouteWithChildren =
  AppSettingsPrivacyAppsProductIdRoute._addFileChildren(
    AppSettingsPrivacyAppsProductIdRouteChildren,
  )

interface AppSettingsPrivacyPermissionsPermissionIdRouteChildren {
  AppSettingsPrivacyPermissionsPermissionIdProductIdRoute: typeof AppSettingsPrivacyPermissionsPermissionIdProductIdRoute
  AppSettingsPrivacyPermissionsPermissionIdIndexRoute: typeof AppSettingsPrivacyPermissionsPermissionIdIndexRoute
}

const AppSettingsPrivacyPermissionsPermissionIdRouteChildren: AppSettingsPrivacyPermissionsPermissionIdRouteChildren =
  {
    AppSettingsPrivacyPermissionsPermissionIdProductIdRoute:
      AppSettingsPrivacyPermissionsPermissionIdProductIdRoute,
    AppSettingsPrivacyPermissionsPermissionIdIndexRoute:
      AppSettingsPrivacyPermissionsPermissionIdIndexRoute,
  }

const AppSettingsPrivacyPermissionsPermissionIdRouteWithChildren =
  AppSettingsPrivacyPermissionsPermissionIdRoute._addFileChildren(
    AppSettingsPrivacyPermissionsPermissionIdRouteChildren,
  )

interface AppSettingsRouteChildren {
  AppSettingsAppearanceRoute: typeof AppSettingsAppearanceRoute
  AppSettingsChatsRoute: typeof AppSettingsChatsRoute
  AppSettingsDevelopmentRoute: typeof AppSettingsDevelopmentRouteWithChildren
  AppSettingsLanguageRoute: typeof AppSettingsLanguageRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppSettingsPrivacyAppsProductIdRoute: typeof AppSettingsPrivacyAppsProductIdRouteWithChildren
  AppSettingsPrivacyPermissionsPermissionIdRoute: typeof AppSettingsPrivacyPermissionsPermissionIdRouteWithChildren
  AppSettingsPrivacyAppsIndexRoute: typeof AppSettingsPrivacyAppsIndexRoute
  AppSettingsPrivacyPermissionsIndexRoute: typeof AppSettingsPrivacyPermissionsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAppearanceRoute: AppSettingsAppearanceRoute,
  AppSettingsChatsRoute: AppSettingsChatsRoute,
  AppSettingsDevelopmentRoute: AppSettingsDevelopmentRouteWithChildren,
  AppSettingsLanguageRoute: AppSettingsLanguageRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppSettingsPrivacyAppsProductIdRoute:
    AppSettingsPrivacyAppsProductIdRouteWithChildren,
  AppSettingsPrivacyPermissionsPermissionIdRoute:
    AppSettingsPrivacyPermissionsPermissionIdRouteWithChildren,
  AppSettingsPrivacyAppsIndexRoute: AppSettingsPrivacyAppsIndexRoute,
  AppSettingsPrivacyPermissionsIndexRoute:
    AppSettingsPrivacyPermissionsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppChatChar123ChatIdChar125Route: typeof AppChatChar123ChatIdChar125Route
  AppNewTabIdRoute: typeof AppNewTabIdRoute
  AppProductIdChar123RouteChar125Route: typeof AppProductIdChar123RouteChar125Route
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppFavoritesRoute: AppFavoritesRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppChatChar123ChatIdChar125Route: AppChatChar123ChatIdChar125Route,
  AppNewTabIdRoute: AppNewTabIdRoute,
  AppProductIdChar123RouteChar125Route: AppProductIdChar123RouteChar125Route,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  CallRoute: CallRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
